version: '3.5'

networks:
  location-integration-test-network:
    name: location-integration-test-network

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: locations
      POSTGRES_USER: locationservice
      POSTGRES_PASSWORD: password
    ports:
      - 7432:5432
    networks:
      - location-integration-test-network
